version: "3"

services:
  load-balance:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - gerencial-network
    depends_on:
      - gerencial-front

  gerencial-front:
    container_name: gpa-gerencial-front
    image: gpa_tributario/gerencial_front:latest
    ports:
      - "4200:4200"
    networks:
      - gerencial-network
    restart: always

networks:
  gerencial-network:
    driver: bridge