version: "3"

services:
  load-balance:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - gerencial-network
    depends_on:
      - gerencial-front


  gerencial-front:
    container_name: gpa-gerencial-front
    image: vinifontana/gerencial_front:latest
    networks:
      - gerencial-network
    depends_on:
      - gerencial-api


  gerencial-api:
    container_name: gpa-gerencial-api
    image: vinifontana/gerencial:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: aws
      WEBSOCKET_ORIGEM: "http://viniciusfontana.com.br"
      TZ: "America/Sao_Paulo"
    networks:
      - gerencial-network
    depends_on:
      - mongo-db
    restart: always


  mongo-db:
    container_name: mongo-db
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "test"
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
    networks:
      - gerencial-network
    restart: always


networks:
  gerencial-network:
    driver: bridge