version: "3"

services:
  load-balance:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - gerencial-network
    depends_on:
      - gerencial-front

  gerencial-front:
    container_name: gerencial-front
    image: vinifontana/gerencial_fron:latest
    networks:
      - gerencial-network
    depends_on:
      - gerencial-api
    restart: always

  gerencial-api:
    container_name: gerencial-api
    image: gpa_tributario/gerencial:latest
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATABASE: "host.docker.internal"
      PORT: 27017
      TZ: "America/Sao_Paulo"
    networks:
      - gerencial-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  gerencial-network:
    driver: bridge