version: "3"

services:
  load-balance:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - gerencial-network
    depends_on:
      - gerencial-front

  gerencial-front:
    container_name: gpa-gerencial-front
    image: gpa_tributario/gerencial_front:latest
    networks:
      - gerencial-network
    depends_on:
      - gerencial-api


  gerencial-api:
    container_name: gpa-gerencial-api
    image: gpa_tributario/gerencial:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATABASE: "host.docker.internal"
      PORT: 27017
      WEBSOCKET_ORIGEM: "http://localhost"
      TZ: "America/Sao_Paulo"
    networks:
      - gerencial-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  gerencial-network:
    driver: bridge